### ISSUE TITLE
Feature request: Crowdin integration

### ISSUE THREAD

**Issue by samuk** [symbiota-coop/dandelion#37]
Adding support for https://developer.crowdin.com/api/v2/

Would enable Human or ML translation of Dandelion sites

**Comment by stephenreid321** [comment]
Hadn't heard of that, looks cool. What's your use case, out of interest?

**Comment by samuk** [comment]
I want to use the Crowdin autodetect browser language to translate Dandelion content that's embeed in an iframe using DeepL
